spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: image-service
      repositories:
        enabled: true

scrapbook:
  googledrive:
    service:
        baseurl: http://gdrive:9090
  metadata:
        baseurl: http://mde:12000/metadata/match