spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: image-service
      repositories:
        enabled: true

scrapbook:
  googledrive:
    service:
        baseurl: http://localhost:9090
  metadata:
        baseurl: http://localhost:12000/metadata/match