spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/image-service
      #      host: localhost
      #      port: 27017
      #      database: image-service
      repositories:
        enabled: true

scrapbook:
  googledrive:
    service:
      baseurl: http://localhost:9090