pipeline {
    agent any

    stages {

       stage('Clone repository') {
            /* Checking out to the repository */
            checkout scm
        }

        stage('Prepare repository') {
            /* Copying the subdir to the parent */
            sh "cp -a ./scrapbook-image-service/. ."
            /* Removing sub directory */
            sh "rm -rf ./scrapbook-image-service"
        }

        stage ('Compile Stage') {

            steps {
                withMaven(maven : 'Maven 3.6.3') {
                    sh 'mvn clean install'
                }
            }
        }

        stage ('Testing Stage') {

            steps {
                withMaven(maven : 'Maven 3.6.3') {
                    sh 'mvn test'
                }
            }
        }
        stage ('Deployment Stage') {
            steps {
                withMaven(maven : 'Maven 3.6.3') {
                    sh 'mvn deploy'
                }
            }
        }
    }
}