node {
    def app
    def registry = 'hrishikeshpaul/scrapbook-image-service'
    def registryCredential = 'docker-hub-credentials'
    def file = 'scrapbook-image-service'
    def masterIP = '149.165.169.58'
    def deploymentName = 'sb-image'
    def user = 'ubuntu'

    stage('Clone repository') {
        /* Checking out to the repository */
        checkout scm
    }

    stage('Prepare repository') {
        /* Copying the subdir to the parent */
        sh "cp -a ./${file}/. ."
        /* Removing sub directory */
        sh "rm -rf ./${file}"
    }

    stage('Build repository') {
        /* Installing application dependencies */
		sh 'mvn -X clean install'
	}

	stage('Test repository') {
        /* Testing the application */
		sh 'mvn test'
	}

    stage('Building image') {
        /* Building the docker image */
        app = docker.build(registry)
	}

    stage('Pushing image') {
        /* Pushing image to docker hub */
        docker.withRegistry('https://registry.hub.docker.com', registryCredential ) {
            app.push("latest")
        }
	}

	stage('Deploy on Kubernetes'){
        /* SSH-ing to Kubernetes master and applying config */
        sshagent(["kube-ssh"]) {
            sh "scp ${file}.yaml ${user}@${masterIP}:/home/${user}"
            sh "ssh ${user}@${masterIP} kubectl delete deployments --ignore-not-found=true ${deploymentName}"
            sh "ssh ${user}@${masterIP} kubectl apply -f ${file}.yaml"
        }

    }
}
