version: "3"
services:
  redis:
    image: redis
    container_name: redis

  scrapbook-session-service:
    container_name: scrapbook-session-service
    image: scrapbook-session-service
    build: .
    ports:
      - "3500:3500"
    links:
      - redis
    networks:
      - scrapbook_network
    
networks: 
  scrapbook_network:
    driver: bridge