apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sb-session
  name: sb-session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-session
  template:
    metadata:
      labels:
        app: sb-session
    spec:
      containers:
      - image: chiragindi/scrapbook-staging-session-service
        name: sb-session
        imagePullPolicy: Always
        ports:
        - containerPort: 3500
        env:
          - name: REDIS_PORT
            value: "12063"
          - name: REDIS_HOST
            value: "redis-12036.c258.us-east-1-4.ec2.cloud.redislabs.com"
          - name: REDIS_PASSWORD
            value: "yB9mUW4ewuSwoVmhlD3UaobRWWrWoLgX"
          - name: MONGO_URI
            value: "mongodb+srv://admin:scrapbook_admin@cluster0.zn4pk.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-session
  name: sb-session
spec:
  selector: 
    app: sb-session
  ports:
  - port: 3500
    targetPort: 3500
