---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: http-kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-kafka
  template:
    metadata:
      labels:
        app: http-kafka
        id: "0"
    spec:
      containers:
      - name: http-kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "http-sb-kafka"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://http-sb-kafka:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: http-zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: "image:1:1"
---
apiVersion: v1
kind: Service
metadata:
  name: http-sb-kafka
  labels:
    name: http-kafka
spec:
  ports:
    - port: 9092
      name: http-kafka-port
      protocol: TCP
  selector:
    app: http-kafka
    id: "0"
  type: ClusterIP
