node {
    def app
    def registry = 'hrishikeshpaul/scrapbook-user-service'
    def registryCredential = 'docker-hub-credentials'

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    // need to have only 'backend' subdir content on the root level
    stage('Prepare repository') {
        // The -a option is an improved recursive option, that preserve all file attributes, and also preserve symlinks.
        // The . at end of the source path is a specific cp syntax that allow to copy all files and folders, included hidden ones.
        sh "cp -a ./scrapbook-user-service/. ."
        sh "rm -rf ./scrapbook-user-service"
        // List the final content
        sh "ls -la"
    }

    stage('Building image') {
        docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
		    def buildName = registry + ":$BUILD_NUMBER"
            app = docker.build buildName
            app.push()
        }
	  } 

    stage('Test image') {
        docker.image(registry).withRun("-p 3000:3000") {
            sh 'npm run test'
        }
    }


    stage('Registring image') {
        docker.withRegistry('https://' + registry, registryCredential ) {
    		app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
	}
    stage('Removing image') {
        sh "docker rmi $registry:$BUILD_NUMBER"
        sh "docker rmi $registry:latest"
    }
    
}