spring:
  application:
    name: GoogleDriveService
  servlet:
    multipart:
      max-file-size: 3GB

  kafka:
    #    consumer:
    #      bootstrap-servers: localhost:9092
    #      group-id: group_id
    #      auto-offset-reset: earliest
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.apache.kafka.common.serialization.StringSerializer

google:
  service:
    account:
      key: classpath:keys/scrapbook.json

server:
  port: 9090