scrapbook:
  image:
    service:
      baseurl: ${IMG}
server:
  port: ${PORT}

topic : ${TOPIC}

spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA}
      key-serializer: com.iu.scrapbook.serializer.MessageSerializer
      value-serializer: com.iu.scrapbook.serializer.MessageSerializer
