node {
    def app
    def registry = 'hrishikeshpaul/scrapbook-ui'
    def registryCredential = 'docker-hub-credentials'

    stage('Clone repository') {
        /* Checking out to the repository */
        checkout scm
    }

    stage('Prepare repository') {
        /* Copying the subdir to the parent */
        sh "cp -a ./scrapbook-ui/. ."
        /* Removing sub directory */
        sh "rm -rf ./scrapbook-ui"
    }

    stage('Build repository') {
        /* Installing application dependencies */
		sh 'npm install'
	}

    stage('Building image') {
        /* Building the docker image */
        app = docker.build(registry)
	} 

    stage('Pushing image') {
        /* Pushing image to docker hub */
        docker.withRegistry('https://registry.hub.docker.com', registryCredential ) {
            app.push("latest")
        }
	}

    stage('Deleting local image') {
        /* Removing locally built images to clear up space */
        sh "docker rmi ${registry}:latest"
        sh "docker rmi registry.hub.docker.com/${registry}:latest"
    }
}