AUTH_SERIVCE_URL__DEV = 'http://localhost:5000'
USER_SERVICE_URL__DEV = 'http://localhost:3000'
SESSION_SERVICE_URL__DEV = 'http://localhost:3500'
IMAGE_SERVICE_URL__DEV = 'http://localhost:8080'
G_DRIVE_SERVICE_URL__DEV = 'http://localhost:9090'