node {
  def app
  def registry = 'hrishikeshpaul/scrapbook-gateway-service'
  def registryCredential = 'docker-hub-credentials'

  stage('Clone repository') {
    /* Checking out to the repository */
    checkout scm
  }

  stage('Prepare repository') {
    /* Copying the subdir to the parent */
    sh "cp -a ./scrapbook-gateway-service/. ."
    /* Removing sub directory */
    sh "rm -rf ./scrapbook-gateway-service"
  }

  stage('Build repository') {
    /* Installing application dependencies */
		sh 'pip3 install -r requirements.txt'
	}

	stage('Test repository') {
        /* Testing the application */
		sh 'python3 -m pytest -v'
	}

    stage('Building image') {
        /* Building the docker image */
        app = docker.build(registry)
	} 

    stage('Pushing image') {
        /* Pushing image to docker hub */
        docker.withRegistry('https://registry.hub.docker.com', registryCredential ) {
            app.push("latest")
        }
	}
}