apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sb-metadata
  name: sb-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-metadata
  template:
    metadata:
      labels:
        app: sb-metadata
    spec:
      containers:
      - image: chiragindi/scrapbook-staging-metadata-service
        name: sb-metadata
        imagePullPolicy: Always
        ports:
        - containerPort: 12000
        env:
          - name: DEBUG
            value: "True"
          - name: PORT
            value: "12000"
          - name: MONGO_URI
            value: "mongodb+srv://admin:EA5URTvI5eh0e6cp@cluster0.zn4pk.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
          - name: KAFKA_URI
            value: "sb-kafka:9092"
          - name: KAFKA_TOPIC
            value: "image"
          - name: G_DRIVE_SERVICE
            value: "http://sb-gdrive:9090"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-metadata
  name: sb-metadata
spec: 
  type: LoadBalancer
  selector: 
    app: sb-metadata
  ports:
  - port: 12000
    targetPort: 12000
    nodePort: 30005
