name: Scrapbook Image Service CI

on:
  workflow_dispatch:
  push:
    branches: [ main-image-service ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        with:
          ref: 'main-image-service'
        
      - uses: actions/setup-java@v1
        with:
          java-version: '15.0.1'
          java-package: jdk
          architecture: x64
          
      - name: Install dependencies
        working-directory: ./scrapbook-image-service
        run: mvn clean install
        
      - name: Test Service
        working-directory: ./scrapbook-image-service
        run: mvn test

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Build Docker Image
        working-directory: ./scrapbook-image-service
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/scrapbook-image-service:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/scrapbook-image-service:latest
