name: scrapbook-user-service CI
on:
  push:
    branches: [ main-user-service ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Install node dependencies
        working-directory: ./scrapbook-user-service
        run: npm ci
      
      - name: Test repository
        run: npm run test

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: hrishikeshpaul/scrapbook-user-service:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
