name: Scrapbook User Service CI

on:
  workflow_dispatch:
  push:
    branches: [main-user-service]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        working-directory: ./scrapbook-user-service
        run: npm install
        
      - name: Test dependencies
        working-directory: ./scrapbook-user-service
        run: npm test
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./scrapbook-user-service/Dockerfile
          push: true
          tags: hrishikeshpaul/scrapbook-user-service:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
